# Generated by Django 3.2.19 on 2023-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
