# Generated by Django 3.2.19 on 2023-08-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
    ]
