# Generated by Django 3.2.19 on 2023-08-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.AddField(
            model_name='friend',
            name='receiver_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_friend_request', to='feed.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='feed.profile'),
        ),
    ]
