# Generated by Django 3.2.19 on 2023-08-23 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0017_user_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_Rooms',
            new_name='User_Room',
        ),
    ]
