# Generated by Django 3.2.19 on 2023-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_auto_20230824_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
