# Generated by Django 3.2.19 on 2023-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20230826_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
