# Generated by Django 3.2.19 on 2023-08-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
