# Generated by Django 3.2.19 on 2023-08-27 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0035_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.CharField(default=None, max_length=10000)),
                ('Reply', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed.reply')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replied_post', to='feed.post')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replied_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
