# Generated by Django 3.2.19 on 2023-08-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0039_post_no_of_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_post',
            name='to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shared_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
