# Generated by Django 3.2.19 on 2023-09-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0044_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
