# Generated by Django 3.2.19 on 2023-09-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0048_alter_activity_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
